import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "next-themes";
import Navbar from "./components/navbar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className="min-h-screen bg-primary transition-all duration-300 ">
        <ThemeProvider attribute="class" enableSystem defaultTheme="system">
          <Navbar/>
          <div className="fixed top-20 left-1/2 -translate-x-1/2
                  h-px w-90 md:w-370
                  bg-stone-600/40 z-40" />
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
